---
- name: Set roles
  ansible.builtin.set_fact:
    roles_list: []

- name: Get roles
  ansible.builtin.find:
    path: "{{ r_tempfile.path }}/{{ collection.name }}/roles/"
    file_type: directory
  register: r_roles

- name: Set collections
  ansible.builtin.set_fact:
    roles_list: "{{ roles_list | default([]) + [item | ansible.builtin.basename] }}"
  loop: "{{ r_roles['files'] | map(attribute='path') | flatten }}"

- name: Cleanup readme
  ansible.builtin.lineinfile:
    path: "{{ r_tempfile['path'] }}/{{ collection.name }}/roles/{{ item }}/README.md"
    regex: '---'
    state: absent
  loop: "{{ roles_list }}"

- name: Remove join(',') that causes issues
  ansible.builtin.replace:
    path: "{{ r_tempfile['path'] }}/{{ collection.name }}/roles/{{ item }}/README.md"
    regexp: "{{ _regex }}"
    replace: ''
  loop: "{{ roles_list }}"
  vars:
    _regex: \| map\(attribute='name'\) \| join\(','\)

- name: Update readme
  ansible.builtin.lineinfile:
    path: "{{ r_tempfile['path'] }}/{{ collection.name }}/roles/{{ item }}/README.md"
    insertbefore: BOF
    line: |
      ---
      layout: default
      title: {{ item }}
      parent: {{ collection.namespace }}.{{ collection.name }}
      ---
  loop: "{{ roles_list }}"

- name: Copy and rename readme
  ansible.builtin.copy:
    src: "{{ r_tempfile['path'] }}/{{ collection.name }}/roles/{{ item }}/README.md"
    dest: "../collections/{{ collection.name }}/{{ item }}.md"
    remote_src: true
    mode: "0644"
  loop: "{{ roles_list }}"

- name: Create collection index page
  ansible.builtin.template:
    src: collection_index.md.j2
    dest: "../collections/{{ collection.name }}/index.md"
    mode: "0644"
  vars:
    collection_name: "{{ collection.name }}"
    collection_namespace: "{{ collection.namespace }}"
...
