---
- name: Generate index
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    collection_list:
      - name: controller_configuration
        namespace: infra
        repo: https://github.com/redhat-cop/controller_configuration.git
      - name: ah_configuration
        namespace: infra
        repo: https://github.com/ansible/galaxy_collection.git
      - name: eda_configuration
        namespace: infra
        repo: https://github.com/redhat-cop/eda_configuration.git
      - name: aap_utilities
        namespace: infra
        repo: https://github.com/redhat-cop/aap_utilities.git
      - name: ee_utilities
        namespace: infra
        repo: https://github.com/redhat-cop/ee_utilities.git
  tasks:
    - name: Delete directories
      ansible.builtin.file:
        path: "../collections"
        state: absent
        mode: "0755"

    - name: Create collections directory
      ansible.builtin.file:
        path: "../collections"
        state: directory
        mode: "0755"

    - name: Create sub directories
      ansible.builtin.file:
        path: "../collections/{{ item.name }}"
        state: directory
        mode: "0755"
      loop: "{{ collection_list }}"

    - name: Create temporary direcotry
      ansible.builtin.tempfile:
        state: directory
        suffix: temp
      register: r_tempfile

    - name: Create temporary directories
      ansible.builtin.file:
        path: "{{ r_tempfile['path'] }}/{{ item.name }}"
        state: directory
        mode: "0755"
      loop: "{{ collection_list }}"

    - name: Clone collections
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ r_tempfile['path'] }}/{{ item.name }}/"
        single_branch: true
        version: devel
      loop: "{{ collection_list }}"

    - name: Loop through each collection
      ansible.builtin.include_tasks: fix_readme.yml
      loop: "{{ collection_list }}"
      loop_control:
        loop_var: collection
        index_var: nav_order
...
